"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = require("fs");
const globN = require("glob");
const mkdirp = require("mkdirp");
const rimraf = require("rimraf");
const util_1 = require("util");
exports.createDir = util_1.promisify(mkdirp);
exports.removeDir = util_1.promisify(rimraf);
exports.glob = (pattern) => util_1.promisify(globN)(pattern);
exports.copyFile = util_1.promisify(fs_1.copyFile);
